### ISSUE TITLE
Question: what ccs element to modify to get a colored titlebar?

### ISSUE THREAD

**Issue by Trikenstein** [vinceliuice/vimix-gtk-themes#241]
Hi,

Using Ubuntu 22.04.1, Gnome 42.4

This theme is excellent. The `install.sh` is very well done. Thanks very much
 
Can you please show me what to modify in the `*.css` to transform the titlebar from grey to a colored accent same as the theme color. The one I am using is 

```shell
./install.sh -t beryl -c dark -s compact --tweaks flat
```

I edited the `~/.themes/vimix-dark-compact-beryl/gtk-3.0/gtk-dark.css` by appending at the end of the file the following css code:

```css
.titlebar, headerbar {
  background-color: #00827f;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #004947;
}
```

This seems to work for GTK3 apps like Gnome terminal. But not working for GTK2 apps like Audacious, Bitwarden, VSCode. And not at all for GTK4 app like Nautilus. Doing the same efit above in the `*.css` files in the `gtk-4.0` directory has no effects in the titlebar color,
