### ISSUE TITLE
Wrong background color on mate panel for "mixed" themes

### ISSUE THREAD

**Issue by Tichy** [vinceliuice/Vimix-gtk-themes#278]
Mate version: 1.28.2

I installed the themes using the install.sh script. The installation ended well without errors.

The issue that I have is that the mate panel mate is colored in white background with white text.
![Image](https://github.com/user-attachments/assets/bc61f9d3-543b-4172-b8f6-ed985d7e664b)

It should be dark with white text
![Image](https://github.com/user-attachments/assets/7d8c302b-3aab-4b4f-b0f5-d984f3ad8e12)

I was able to find the style to fix inside the generated gtk3 gtk.css file:

Example for Vimix-doder at line 7214
``` css
#PanelPlug,
PanelToplevel.background {
  background-color: #292B2E;
  color: rgba(0, 0, 0, 0.6);
  font-weight: 500;
}
```

But I don't know how to fix it inside the templates in `_sass` to obtain the fixed css files when generating them with the install.sh script, otherwise I would have made a branch and a pull request with the fix.
